# Name of website
title: "Nihongo note"
description: "A blog about learning Japanese"

show_download: true
# theme: minima
theme: jekyll-theme-slate
# theme: jekyll-theme-time-machine
# theme: jekyll-theme-architect

encoding: utf-8
